name: Deploy on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: cd frontend && yarn install

      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s) &&
          ssh-add ~/.ssh/deploy_key &&
          ssh-add -l


      - name: Set up git vars
        run: |
          git config --global user.email "irnsght@googlemail.com"
          git config --global user.name "IR0NSIGHT"
          git remote set-url origin git@github.com:IR0NSIGHT/AdvancedOperationGUI.git

      - name: Run yarn deploy on new tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run:
          cd frontend &&
          yarn deploy
